### ISSUE TITLE
Creating batched IntegrationJob does not work properly

### ISSUE THREAD

**Issue by cqbqdd11519** [tmax-cloud/cicd-operator#270]
## Pull Requests in the Merge Pool
- #264
- #268

## Expected `IntegrationJob`'s refs
```yaml
  refs:
    base:
      link: https://github.com/tmax-cloud/cicd-operator/pull/264
      ref: master
      sha: c981aa4fa5c3207c5d5b3fbce766bfecdde406ec
    link: https://github.com/tmax-cloud/cicd-operator/pull/264
    pulls:
    - author:
        name: cqbqdd11519
      id: 264
      link: https://github.com/tmax-cloud/cicd-operator/pull/264
      ref: feat/add-expose-controller
      sha: 202a0090a5e683eaec04446c3eb01f5480b941bc
    - author:
        name: cqbqdd11519
      id: 268
      link: https://github.com/tmax-cloud/cicd-operator/pull/268
      ref: feat/add-sender-env
      sha: 81a7c0b9b972ce408c80369fd907e38079498ddf
    repository: tmax-cloud/cicd-operator
    sender:
      email: bot@cicd.tmax.io
      name: tmax-cicd-bot
```

## Actual `IntegrationJob`'s refs
```yaml
  refs:
    base:
      link: https://github.com/tmax-cloud/cicd-operator/pull/264
      ref: master
      sha: c981aa4fa5c3207c5d5b3fbce766bfecdde406ec
    link: https://github.com/tmax-cloud/cicd-operator/pull/264
    pulls:
    - author:
        name: cqbqdd11519
      id: 264
      link: https://github.com/tmax-cloud/cicd-operator/pull/264
      ref: feat/add-expose-controller
      sha: 202a0090a5e683eaec04446c3eb01f5480b941bc
    - author:
        name: cqbqdd11519
      id: 264
      link: https://github.com/tmax-cloud/cicd-operator/pull/264
      ref: feat/add-expose-controller
      sha: 202a0090a5e683eaec04446c3eb01f5480b941bc
    repository: tmax-cloud/cicd-operator
    sender:
      email: bot@cicd.tmax.io
      name: tmax-cicd-bot
```
